### ISSUE TITLE
Homebrew formula on OS X?

### ISSUE THREAD

**Issue by nbastin** [kaishuu0123/erd-go#2]
This is super neat - any chance we could get a homebrew (https://brew.sh/) formula for MacOS X rather than a binary download?  It would integrate well with the way most people get dot (from the graphviz formula) and would gracefully isolate from the rest of the system.

**Comment by kaishuu0123** [comment]
@nbastin 

Thank you for your comment.
Do you have any information to be helpful?

Or is there a repository doing the same?

**Comment by kaishuu0123** [comment]
I understand.
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by kaishuu0123** [comment]
I created homebrew repository.
I'll send PR to homebrew-core.

now 

```
brew tap kaishuu0123/erd-go
brew install erd-go
```

https://github.com/kaishuu0123/homebrew-erd-go

**Comment by nbastin** [comment]
This is fantastic!  Thanks for looking into it.

**Comment by kaishuu0123** [comment]
sent to homebrew-core. ( https://github.com/Homebrew/homebrew-core/pull/30343 )
but `Unfortunately this doesn't meet our notability requirements`

> * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)

I wanted to provide erd-go with homebrew-core.
That's a shame.

close this issue.

@nbastin 

enjoy!
